name: Teleport Setup
author: Gravitational, Inc.
description: Installs `teleport`, `tsh`, `tbot` and `tctl`.
inputs:
    enterprise:
        description: Specify whether to use the enterprise binaries.
        required: false
        default: "false"
    version:
        description: Specify the Teleport version without the preceding "v"
        required: true
runs:
    using: node20
    main: dist/index.js
branding:
    color: purple
    icon: terminal
